@startuml
'https://plantuml.com/object-diagram

object p1 {
	id = 2031
    nome = Greg
}

object p2 {
    id = 7513
    nome = John
}

object p3 {
    id = 1394
    nome = Martha
}

object p4 {
    id = 8015
    nome = Chris
}

object c1 {
	id = 1001
	modelo = Fox
	ano = 2015
}

object c2 {
	id = 1002
	modelo = Van Plus
	ano = 2017
}

object c3 {
	id = 1003
	modelo = Cross Hatch
	ano = 2014
}

object c4 {
	id = 1004
	modelo = Convert
	ano = 1998
}

p1 -- c1
p3 -- c2
p3 -- c4
p4 -- c3

@enduml
